./configure -prefix /home/zhangshaoyan/LaserSpy/RK3399/sysrootx64/libqt5110 \
-no-pch \
-qt-sqlite \
-qt-libjpeg \
-qt-libpng \
-evdev \
-linuxfb \
-qpa linuxfb \
-no-opengl \
-qt-harfbuzz \
-qt-freetype \
-no-openssl \
-qt-zlib \
-qt-pcre \
-no-dbus \
-nomake examples \
-qreal float \
-xplatform linux-aarch64-gnu-g++ \
-shared \
-strip \
-release \
-confirm-license \
-c++std c++11 \
-gui -widgets \
-opensource 
